#!/bin/bash
read -p "Type to create your password: " password
PASSWORD=true
echo "Password created successfully"
while "$PASSWORD";
do
	read -p "Enter password for confrimation: " confirmation

	if [[ "$confirmation" == "$password" ]];
	then
		echo "Password confirmed!"
		break
	

	elif [[ "$confirmation" != "$password" && $PASSWORD == true ]];
	then
		echo "Password does not match"


	else 
		echo "Invalid password!"

	fi
	

done
