#!/bin/bash

echo "Welcome to AV(Autonomous Vehichle)!
Available commands

start: To start engine

stop: To stop engine

exit: To terminate AV program

-help: To display available commands
"
SHOULD_EXECUTE=true
ENGINE_IS_ON=false
DRIVING=false
REVERSE=false
PARKING=true

while "$SHOULD_EXECUTE";
do
	read -p "Enter vehicle command: " ACTION

	if [[ "$ACTION" == start && "$ENGINE_IS_ON" == false ]];
	then
		echo "AV engine is starting..."
		sleep 1
		echo "4"
		sleep 1
		echo "3"
		sleep 1
		echo "2"
		sleep 1
		echo "1"
		sleep 1
		echo "Engine has started!"
		echo "
		Select D to drive vehicle
		
		Select P to park vehicle
		
		Select R to reverse vehicle"
		ENGINE_IS_ON=true
		

	elif [[ "$ACTION" == D && "$ENGINE_IS_ON" == true && "$DRIVING" == false ]];
	then
		echo "Initiating drive mode"
		sleep 1
		echo -e "Drive mode initiated \U1F697"
		sleep 1
		echo -e "Driving............................................ \U1F697"
		sleep 1
		echo -e "Drving............................................................................................................... \U1F697"
		sleep 1
		echo -e "Driving................................................................................................................................................................ \U1F697"
		DRIVING=true

	elif [[ "$ACTION" == D && "$DRIVING" == true && "$ENGINE_IS_ON" == true ]];
        then
                echo "The AV is already in drive mode!"


	elif [[ "$ACTION" == R && "$ENGINE_IS_ON" == true && "$REVERSE" == false ]];
	then
		echo "Initiating reverse"
		sleep 1
		echo -e "Reverse mode initiated"
		sleep 1
		echo -e "Reversing.............................................................................................................................................................. \U1F697"
		sleep 1
		echo -e "Reversing............................................................................................................. \U1F697"
		sleep 1
		echo -e "Reversing............................................. \U1F697"
		REVERSE=true

	elif [[ "$ACTION" == R && "$ENGINE_IS_ON" == true && "$REVERSE" == true ]];
	then
		echo "The AV is already in reverse mode"


	
	elif [[ "$ACTION" == stop && "$ENGINE_IS_ON" == true ]];
	then
		echo "Stopping AV engine..."
      		sleep 1
      		echo "4"
      		sleep 1
      		echo "3"
      		sleep 1
      		echo "2"
      		sleep 1
      		echo "1"
      		sleep 1
      		echo "Engine has stopped!"
		ENGINE_IS_ON=false


	elif [[ "$ACTION" == start && "$ENGINE_IS_ON" == true ]];
	then
		echo "Engine is already on"

	elif [[ "$ACTION" == stop && "$ENGINE_IS_ON" == false ]];
	then
		echo "Engine is already off!"

	elif [[ "$ACTION" == P && "$ENGINE_IS_ON" == false ]]
	then
		echo "Initiating parking"
		sleep 1
		echo "Parking..."
		sleep 1
		echo "The AV is parked"


	elif [[ "$ACTION" == -help ]];
	then
		echo "Welcome to AV(Autonomous Vehichle)!
		Available commands

		start: To start engine

		stop: To stop engine

		exit: To terminate AV program

		-help: To display available commands
		"

	elif [[ "$ACTION" == exit ]];
	then
		echo "The AV program has been terminated"
		break

	else
		echo "Invalid Command!"
	fi


done
